apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.app_name}}
  labels:
    app: ${{values.app_name}}
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${{values.app_name}}
      version: v1
  template:
    metadata:
      labels:
        app: ${{values.app_name}}
        version: v1
    spec:
      containers:
      - name: ${{values.app_name}}
        image: ${{values.app_name}}:latest
        ports:
        - containerPort: ${{values.http_port}}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: ${{values.http_port}}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: ${{values.http_port}}
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"