apiVersion: v1
kind: Service
metadata:
  name: ${{values.app_name}}-service
  labels:
    app: ${{values.app_name}}
spec:
  selector:
    app: ${{values.app_name}}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: ${{values.http_port}}
  type: ClusterIP