site_name: ${{values.app_name | title}}
site_description: ${{values.description}}

nav:
  - Home: index.md

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share

plugins:
  - search
  - techdocs-core

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true