apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.app_name}}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${{values.destination.owner}}/${{values.destination.repo}}
    targetRevision: HEAD
    path: charts/${{values.app_name}}
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.app_name}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true