spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.redhat.encryption: DEBUG
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"