apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Python app that displays time - named ${{values.app_name}}
  annotations:
    github.com/project-slug: DaggupatiPavan-1/${{values.app_name}}
    backstage.io/kubernetes-namespace: ${{values.env}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
